### ISSUE TITLE
Consider separating orepan2-audit

### ISSUE THREAD

**Issue by bjakubski** [tokuhirom/OrePAN2#37]
I've noticed that OrePAN2::Auditor is using a bit different set of modules than rest of OrePAN2. Installing OrePAN2 on system with only perl core modules installed seems to require 127 CPAN distributions to be installed first. If I remove dependencies that are used by auditor only we are down to 74 distributions.
Auditor does not seem to be part of "core" OrePAN2 functionality, so it may be worth considering separating it into its own distro (such new distro won't even require OrePAN: auditor does not use any other part of OrePAN)

**Comment by oalders** [comment]
Would you be able to share the chain of deps you're seeing just for OrePAN2::Auditor?  The plan for OrePAN2 moving forward is to convert it to Moo and probably Type::Tiny, so some of these dependencies would be pulled into the main distribution anyway if that were the case.

I'm wondering to which extent Parse::CPAN::Packages is to blame here.

**Comment by bjakubski** [comment]
Parse::CPAN::Packages is the main offender, it pulls PPI (directly) and Moose (through Archive::Peek
) among others. Without Parse::CPAN::Packages only 94 dists are needed for OrePAN2.
http://deps.cpantesters.org/?module=OrePAN2;perl=latest seems to give decent overview of all deps

**Comment by oalders** [comment]
Thanks for this. I'm wondering if https://metacpan.org/pod/Parse::CPAN::Packages::Fast is a better choice, but I think there was a reason I didn't use it initially.  I think because it expects 02packages to be gzipped.  If that were patched, we might be able to switch to that dep.

**Comment by bjakubski** [comment]
So now experimental Parse::CPAN::Packages::Fast release can work with non-gzipped files.
But unfortunately seems that OrePAN::Auditor stil uses something that ::Fast does not implement - ability to pass 02packages file _content_ to new().
This can be worked around in OrePAN (save to temp file and pass that to new()) or ::Fast could implement that (also makes sense, but maybe with API better than "autodetect if string passed to new is filename or not").

**Comment by oalders** [comment]
@bjakubski I think using `content` in the Auditor was done to work around a similar limitation in `Parse::CPAN::Packages`, where you can either have a compressed file or the raw content, but you can't just pass it a text file that isn't zipped.

So, since OrePAN already employs a workaround (and in some cases a temp file), I don't see this as a problem.

@eserte++ for making the change in `Parse::CPAN::Packages::Fast`.

@bjakubski I'm not sure when I'll next get some `$work` time to look at this.  If you're inclined to send a pull request, I'd be happy to merge such a change.

**Comment by oalders** [comment]
Thanks @bjakubski and @eserte!
